language: shell

os:
  - linux
  - osx
  # - windows

env:
  - PYTHON="3.8"
  - PYTHON="3.7"
  - PYTHON="3.6"
  - PYTHON="3"
  - PYTHON="2"

addons:
  homebrew:
    packages:
      - kcov

install:
  - curl -sSL https://git.io/shellspec | sh -s -- -y

before_script:
  - shellspec --syntax-check

script:
  - if [ $TRAVIS_OS_NAME = osx ]; then SHELLSPEC_FLAGS="--kcov"; fi
  - shellspec --no-banner $SHELLSPEC_FLAGS spec/units
  - shellspec --no-banner $SHELLSPEC_FLAGS spec/integration
  - wget https://raw.githubusercontent.com/neimad/travis-python/$TRAVIS_COMMIT/travis-python.bash
  - source travis-python.bash
  - install_python $HOME/Python $PYTHON
  - which python
  - python --version
