language: shell

os:
  - linux
  - osx
  - windows

env:
  - PYTHON=3.8
  - PYTHON=3.7
  - PYTHON=3.6
  - PYTHON=2.7

addons:
  homebrew:
    update: true
    packages:
      - kcov

install:
  - curl -sSL https://git.io/shellspec | sh -s -- -y

before_script:
  - shellspec --syntax-check

script:
  - |
    if [[ $TRAVIS_OS_NAME = osx ]]; then
      SHELLSPEC_FLAGS="--kcov"
    fi
  - shellspec --no-banner $SHELLSPEC_FLAGS spec/units
  - shellspec --no-banner $SHELLSPEC_FLAGS spec/integration
