language: shell

stages:
  - units
  - integration

install:
  - wget https://github.com/shellspec/shellspec/archive/master.tar.gz
  - tar -C $HOME -xzf master.tar.gz
  - PATH=$HOME/shellspec-master:$PATH

jobs:
  include:
    - stage: units
      os: linux
      env:
      before_script: shellspec --syntax-check
      script: shellspec --no-banner spec/units
    - stage: units
      os: osx
      env:
      addons:
        homebrew:
          update: true
          packages:
            - kcov
      before_script: shellspec --syntax-check
      script: shellspec --no-banner --kcov spec/units
    - stage: units
      os: windows
      env:
      before_script: shellspec --syntax-check
      script: shellspec --no-banner spec/units

stage: integration

os:
  - linux
  - osx
  - windows

env:
  - PYTHON=3.8
  - PYTHON=3.7
  - PYTHON=3.6
  - PYTHON=2.7


script: shellspec --no-banner spec/integration
