language: shell

stages:
  - Units
  - Coverage
  - Integration

osx_image: xcode11

install:
  - curl -fsSL https://git.io/shellspec | sh -s -- -y
  - PATH=$HOME/.local/bin:$PATH

jobs:
  include:
    - &units
      stage: Units
      os: linux
      env:
      before_script: shellspec --syntax-check
      script: shellspec --no-banner spec/units
    - <<: *units
      os: osx
    - <<: *units
      os: windows

    - stage: Coverage
      os: osx
      env:
      addons:
        homebrew:
          packages:
            - kcov
      script: shellspec --no-banner --kcov --kcov-options "--coveralls-id=$TRAVIS_JOB_ID" spec/units

stage: Integration
os:
  - linux
  - osx
  - windows
env:
  - PYTHON=3.8
  - PYTHON=3.7
  - PYTHON=3.6
  - PYTHON=2.7
script: shellspec --no-banner spec/integration
