language: shell

os:
  - linux
  - osx
  - windows

env:
  - PYTHON="3.7"
  - PYTHON="3.6"
  - PYTHON="3"
  - PYTHON="2"

install:
  - curl -sSL https://git.io/shellspec | sh -s -- -y

before_script:
  - shellspec --syntax-check

script:
  - shellspec spec/units
  - shellspec spec/integration
