language: shell

os:
  - linux
  - osx
  - windows

env:
  - PYTHON=3.8
  - PYTHON=3.7
  - PYTHON=3.6
  - PYTHON=2.7

addons:
  homebrew:
    update: true
    packages:
      - kcov

install:
  - wget https://github.com/shellspec/shellspec/archive/master.tar.gz
  - tar -C $HOME -xzf master.tar.gz
  - PATH=$HOME/shellspec-master:$PATH

before_script:
  - shellspec --syntax-check

script:
  - |
    if [[ $TRAVIS_OS_NAME = osx ]]; then
      SHELLSPEC_FLAGS="--kcov"
    fi
  - shellspec --no-banner $SHELLSPEC_FLAGS spec/units
  - shellspec --no-banner $SHELLSPEC_FLAGS spec/integration
