language: shell

os:
  - linux
  - osx
  - windows

env:
  - PYTHON="3.7"
  - PYTHON="3.6"
  - PYTHON="3"
  - PYTHON="2"

addons:
  homebrew:
    packages:
      - kcov

install:
  - curl -sSL https://git.io/shellspec | sh -s -- -y

before_script:
  - shellspec --syntax-check

script:
  - if [ $TRAVIS_OS_NAME = osx ]; then SHELLSPEC_FLAGS="--kcov"; fi
  - shellspec $SHELLSPEC_FLAGS spec/units
  # - shellspec $SHELLSPEC_FLAGS spec/integration
