language: shell

os:
  - linux
  - osx
  - windows

env:
  - PYTHON=3.8
  - PYTHON=3.7
  - PYTHON=3.6
  - PYTHON=2.7

addons:
  homebrew:
    packages:
      - kcov

install:
  - |
    if [[ $TRAVIS_OS_NAME != windows ]]; then
      curl -sSL https://git.io/shellspec | sh -s -- -y
    fi

before_script:
  - |
    if [[ $TRAVIS_OS_NAME = windows ]]; then
      source travis-python.bash
    else
      shellspec --syntax-check
    fi

script:
  - |
    if [[ $TRAVIS_OS_NAME = osx ]]; then
      SHELLSPEC_FLAGS="--kcov"
    fi
  - |
    if [[ $TRAVIS_OS_NAME = windows ]]; then
      install_python $HOME/Python $PYTHON
      if [[ $(command -v python) != $HOME/Python/* ]]; then
        echo "Python installed in $(command -v python) instead of $HOME/Python/*."
      fi
      if [[ $(python --version 2>&1) != Python\ $PYTHON* ]]; then
        echo "$(python --version 2>&1) installed instead of $PYTHON*"
      fi
    else
      shellspec --no-banner $SHELLSPEC_FLAGS spec/units
      shellspec --no-banner $SHELLSPEC_FLAGS spec/integration
    fi
